version: '3.8'

db: 
  user: "root"
  password: "1234"
  name: "Example"
  host: "db"
  port: "3306"
minio:
  access_key_id: "elq1BRA1F0MjqEYJTBRJ"
  secret_access_key: "WVdUY7SUQZs7DEQUh8MbNvcD4HGVmBKlpQqaNEvc"
stream:
  name: "IMAGES"

