version: '3.8'

DB_USER: "root"
DB_PASSWORD: "1234"
DB_NAME: "Example"
DB_HOST: "db"
DB_PORT: "3306"
TEST_ENV: "TEST23"
MINIO_ACCESS_KEY_ID: "elq1BRA1F0MjqEYJTBRJ"
MINIO_SECRET_ACCESS_KEY: "WVdUY7SUQZs7DEQUh8MbNvcD4HGVmBKlpQqaNEvc"