version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./apis/main.go -b 0.0.0.0
  db:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
