version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  db:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DB=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ROOT_USER=miniouser
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: 'server /data --console-address ":9001"'

  nats:
    image: nats
    ports:
      - 4222:4222
      - "8222:8222" # Optional: HTTP management port
    command: >
      -js
      --store_dir=/data/nats
    volumes:
      - nats_data:/data/nats
  # # n1:
  #   image: synadia/jsm:nightly
  #   entrypoint: /nats-server
  #   command: "--config ./config/jetstream.conf --server_name S1"

  #   ports:
  #     - 4223:4222
  #   volumes:
  #     - ./stream-config:/config
  #     - ./persistent-data/server-n1/:/data/nats-server/jetstream
  
volumes:
  mysql-data:
  minio-data:
  nats_data: 
    driver: local
