version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  db:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DB=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ROOT_USER=miniouser
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: 'server /data --console-address ":9001"'

  nats:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222
    command: >
      -js
      --store_dir=/data/nats
    volumes:
      - nats_data:/data/nats
  mongodb:
    image: mongo:6.0.8
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
volumes:
  mysql-data:
  mongo-data:
  minio-data:
  nats_data: 
    driver: local
